### ISSUE TITLE
Can I call the nouiSlider has a reset() function?

### ISSUE THREAD

**Issue by michaelzero00** [Lahori-Jawan/veeno#6]
I'd love to reset the slider to the starting values. I've tried binding :handles in my component and adjusting these but it doesn't alter the slider values. Is there a reset() like in nouislider? Thanks.

**Comment by Lahori-Jawan** [comment]
Sadly its not implemented yet but you can work around this in 2 ways:

1. create a custom component & re-render it whenever you want to reset i.e. 

Using `:key` attribute:
```
<veeno :handles="[]" :range="{}"  :key="resetToggle" />
```

2. Use the `set` method to set to `reset` values (which is a hack)
```
<veeno 
    :set="setValue" // <= your function
    :handles="130"
    :range = "{ 
      'min': 100, 
      'max': 350 
    }"
    >
    {{ setValue }}
  </veeno>
```
I still believe there should be an easier way to reset values 🤔️

**Comment by michaelzero00** [comment]
Thanks! Yes I've been forcing the re-render by key change it seems to work fine! As a workaround.
